services:
  turbo-scraper:
    build: .
    container_name: turbo-scraper
    restart: unless-stopped
    env_file:
      - .env
    environment:
      TZ: Asia/Baku
    volumes:
      - ./data:/app/data
      - ./logs:/var/log